### PR TITLE
Add Emojicode support

### PR DESCRIPTION
**Pull request by OttoWinter**
[Emojicode](http://www.emojicode.org) is a delimiter-less, object oriented, imperative, high-level, hybrid language with emojis as fix points and methods.

### CODE REVIEW

**Comment by thbwd** [comment]
http://www.emojicode.org (The link above does not seem to be working.)

**Comment by thbwd** [comment]
Any feedback on this?

**Comment by eqot** [comment]
Sorry for too late reply.
I have merged your commits and published the updated package.
Thanks!

**Comment by OttoWinter** [comment]
Thank you!

**Pull request merged**
